" Show the line and column number of the cursor position
set ruler

" Display the incomplete commands in the bottom right-hand side of your screen.  
set showcmd

" Display completion matches on your status line
set wildmenu

" Highlight search matches. equivalent to :hls. temperory disabled by :nohls
set hlsearch

" Enable incremental searching. equivalent to :is
set incsearch

" Use spaces instead of tabs
set expandtab

" Make a tab equal to 4 spaces
set shiftwidth=4
set tabstop=4

set background=dark
set backspace=2

" let g:netrw_liststyle = 3

" set number