return {
    "tpope/vim-sleuth", -- Detect tabstop and shiftwidth automatically
    --"nvim-lua/plenary.nvim",
    --"hrsh7th/nvim-cmp",
    --"hrsh7th/cmp-nvim-lsp",
    -- require("nvimvscode.plugins.autocomplete"),
    -- require("nvimvscode.plugins.autopairs"),
    -- require("nvimvscode.plugins.colorscheme"),
    require("nvimvscode.plugins.comment"),
    -- require("nvimvscode.plugins.dressing"),
    -- require("nvimvscode.plugins.formatting"),
    -- require("nvimvscode.plugins.gitsigns"),
    -- require("nvimvscode.plugins.indent-blnvimvscodeline"),
    -- require("nvimvscode.plugins.lazydev"),
    -- require("nvimvscode.plugins.lint"),
    -- require("nvimvscode.plugins.lsp"),
    -- require("nvimvscode.plugins.lualine"),
    require("nvimvscode.plugins.mini"),
    -- require("nvimvscode.plugins.neo-tree"),
    -- require("nvimvscode.plugins.nvim-ts-autotag"),
    -- require("nvimvscode.plugins.oil"),
    -- --require("nvimvscode.plugins.substitute"),
    -- require("nvimvscode.plugins.telescope"),
    -- require("nvimvscode.plugins.todo"),
    -- require("nvimvscode.plugins.treesitter"),
    -- require("nvimvscode.plugins.trouble"),
    -- require("nvimvscode.plugins.vim-maximizer"),
    -- require("nvimvscode.plugins.which-key"),
}